/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1e64370c-7d26-43a1-bcfe-d49586f4e9d7",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Mljaaylm9",
    "aws_user_pools_web_client_id": "73cb6ebof0bg8hfh16hsq51kuf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://hdsmpinitnakhor6hlgs34amv4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3ntkn3log5a3bfpw4zjdvdjs7y"
};


export default awsmobile;
